spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mcs_order-service_db?createDatabaseIfNotExist=true
    username: root
    password:
  application:
    name: order-service
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
