spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mcs_product_db?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: product-service


